### ISSUE TITLE
Avoiding tag redundancy when adding annotations to existing tag

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#301] opened 2015-03-20 15:16 UTC
http://apps.testing.cwrc.ca/editor/dev/editor_dev.htm#templates/ceww_new_entry_template

Using this template brings home the problems of annotating existing markup: you end up with duplicate tags and it's hard to figure out which one has the entity and which one should be deleted. 

James or Andrew, can you think of any creative way of dealing with this? Could we add a right click functionality along the lines of "add entity to this tag"?

**Comment by SusanBrown** [comment] 2015-07-28 13:42
@jchartrand Could you review this and suggest how we might proceed ? Right now we end up with two name tags if we annotate a name that is already tagged.

**Comment by jchartrand** [comment] 2015-08-01 10:30
As you suggest, we could add a right click option to add a CWRC entity to an existing tag, but maybe we could also, whenever a selection (of text) is tagged (with a CWRC tag/entity), first programmatically (under the covers) check if the selected text already has a tag (of any sort), and if so, ask the user if they'd like to: 
a) replace the existing tag with the new CWRC tag/entity 
b) add a CWRC entity to the existing tag
Andrew, is this even feasible?

**Comment by ajmacdonald** [comment] 2015-08-05 21:14
The difficulty would be in detecting whether the text selection encompasses all the text in the tag or just some of the text (It can get tricky with things like whitespace). Additionally, each instance of text will already have some sort of tag by definition. Overall I would say it's not very feasible.

a) We already have a "Change Tag" option from the context (right-click) menus. It doesn't currently work with entities, but that could be fixed.
b) This could be added to the current context menus.

In general, it's much more reliable to add tags through the markup tree, than to try to select exactly the right amount of text inside of a parent tag.

**Comment by SusanBrown** [comment] 2015-08-13 14:04
Maybe we should start by allowing “change tag” to allow people to change a tag to an entity tag. But where there are existing attributes and what one is really doing is creating an entity to go with the tag it would be nice not to lose the existing attributes? Could we have a “Convert to entity” tag that is available only when the selected tag corresponds to an entity?

**Comment by ajmacdonald** [comment] 2015-08-13 21:14
1) Yes it's possible to keep existing attributes.
2) Yes it's possible to have a "convert to entity" option available only when the tag corresponds to an entity.

We should maybe think in general about how we deal with tags that correspond to entities, but which do not currently have an associated entity. Currently, the only way to end up in this situation is when loading a document that's been created outside of CWRC-Writer (e.g. the templates). Otherwise, if you try to add a tag through any of the tag menus and it corresponds to an entity (e.g. persName), you're sent to the appropriate entity dialog instead of the normal tag dialog. Would it therefore make sense to analyze the document upon loading and automatically create entity entries for the tags that are relevant? Doing this would sidestep the tag redundancy issue.

**Comment by ilovan** [comment] 2015-08-18 06:05
Would it be possible to do this automatic conversion from within CWRC Writer at this point? Do we have any idea how/if it would interfere with the code of the Islandora CWRC-Writer integration module?

**Comment by ilovan** [comment] 2015-08-18 15:36
Summary of discussion with James and Susan (Aug 18):
Automatic conversion to be tabled for now (it will be possible to do it once the Entity recognition work is integrated into CWRC Writer)

For now:
Add "Convert to entity" button in the right-click menu of tags that have mappings to entities.
* If the tag has a ref attribute with an URI value specified, create the entity reference from that URI.
* If the tag does not have a ref attribute with an URI value specified, open the entity lookup and proceed from there.

Also, keep the attribute values, not only the tags.

**Comment by ajmacdonald** [comment] 2015-08-20 19:58
This is in place now, however I'm not closing the issue because it needs testing by others to ensure it's what you had in mind.

**Comment by ilovan** [comment] 2015-08-25 18:34
Just tested briefly: 

General observation: the "Convert to entity" button should be available from the "markup panel" right-click menu as well as from the text area right-click menu. 

Both Orlando and CWRC schemas (haven't tried TEI yet, but I suspect it's the same): the process is working only for the first attempt. (i.e. if the user tries to convert a second entity in the same document or another document, nothing happens, though the menu item to do so is available. Clearing the cashe doesn't change this behaviour.


the Orlando bio sample: 
Managed to convert an orgname, but after I selected the entity in the entity lookup dialogue, I got the standard name popup window, which is a part of the XML tagging process.

**Comment by ajmacdonald** [comment] 2015-08-27 16:28
Ok I'll add the option to the markup panel menu.

I can't reproduce your issue re: being unable to convert multiple entities.

Re: the XML tagging process, this is part of editing an entity or tag, which is basically what you're doing during the conversion.

**Comment by ilovan** [comment] 2015-08-31 23:25
OK, I tested this more thoroughly now:

"Convert to entity" in the right-click menu of the structure panel  works for all types of entities, but, if in the entity lookup panel the user decides to cancel, the entity is still created. 

 "Convert to entity" in the right-click menu in the text area works only if the cursor is already inside the tag to be converted (i.e. if the user right-clicks directly inside the name tag, the "Convert to entity" option in the menu that pops up is grayed out; if the user clicks first in the name tag and then right-clicks, the "Convert to entity" option will be available; incidentally, the right-click in that case highlights only one word inside the tag, which may lead the user to believe that the annotation would be affixed to only the portion of the name represented by that word).

**Comment by ajmacdonald** [comment] 2015-09-02 17:38
First issue is now fixed.
I couldn't reproduce the second issue.

**Comment by ilovan** [comment] 2015-09-02 18:47
I can reproduce it on different computers in both Chrome and Firefox. Suggestions?

**Comment by ajmacdonald** [comment] 2015-09-02 22:11
Are you on Mac or PC?

**Comment by ilovan** [comment] 2015-09-02 22:12
A Mac. The other Computer I tried it on is also a Mac.

**Comment by ajmacdonald** [comment] 2015-09-08 18:06
@ilovan I've attempted a fix. Please test and let me know if it helps.

**Comment by ilovan** [comment] 2015-09-08 22:53
Tested the two issues I mentioned in the previous comment:

Hitting "Cancel" in the "Convert to entity" entity dialog box no longer creates an entity, but the tag itself is no longer visible in the structure panel after its conversion to entity has been canceled. (it's still visible in the text area if "show tags" is on).

Second issue:
Fixed.

Another minor thing: the "Convert to entity" buttons in the two right-click menus (structure panel and text area) are positioned either at the top (the former) or the bottom (the later). 
I think the "convert to entity" menu option should be consistently placed in the same are of the right-click menu. I suggest after "Remove tag", as in:
![screen shot 2015-09-08 at 4 50 11 pm](https://cloud.githubusercontent.com/assets/6600070/9749426/0fbf1fd0-564a-11e5-8712-4d97aa387c78.png)

**Comment by ilovan** [comment] 2015-09-08 23:12
Also, in the Orlando schema, if a place tag contains multiple child elements, it cannot be converted to a place entity. For example, I can convert Canada, but not Brampton, Ontario.

**Comment by ajmacdonald** [comment] 2015-09-09 17:52
The structure panel menu has 3 remove tag options. Should "convert to entity" go below all of them?

**Comment by ajmacdonald** [comment] 2015-09-09 18:44
Fixed the first issue.

**Comment by ajmacdonald** [comment] 2015-09-09 20:12
Re: the place tag issue, the current implementation of the place entity assumes there will be only one child element. Conversion to a place entity with multiple child elements is a complex problem and would also require reworking how the place entity tagging form works.

**Comment by ilovan** [comment] 2015-09-19 05:44
This is a discussion we need to have internally, @SusanBrown and @brundin . It is a problem specific to Orlando and we need to decide how we would like to proceed.

**Comment by susanirenebrown** [comment] 2015-09-19 11:06
I’m not sure I understand the problem but am trying to weigh in anyway, ready to be corrected.

Is it not possible to put the URI on the surrounding PLACE tag and ignore the child tags? I say this presuming that there could be more than one child tag in a PLACENAME tag, just not child tags to do with place. But obviously this is not possible if what Andrew says is literally true.

**Comment by brundin** [comment] 2015-09-21 21:39
Not sure I fully understand the problem either.  All of our core named elements in the CWRC entry and Orlando schemas (i.e., the NAME, ORGNAME, PLACE, and TITLE elements) that can link to the associated named entity (i.e., person, organization, place, and title) via a URL in the REF attribute can contain multiple child elements.  For example, ORGNAME can contain child elements of DENOMINATION, EMPH, FOREIGN, POLITICALAFFILIATION, etc.   This is also true for the analogous TEI elements of persName, orgName, placeName, and title that can link to named entities via their ref attributes (i.e., these elements can contain multiple child elements).

It may be in that in the templates and samples that we have created, none of the entity reference elements had more than one child element.  Or more specifically, had no child elements, so that the text node of the container entity reference element could be assumed to contain the entire string that would be used for the entity lookup in the CWRC repository, VIAF, GeoNames, or Google Geocode.  I.e., this query lookup string would not be parsed into more granular child elements as can occur with the Orlando PLACE element, which can be parsed into the following child elements: ADDRESS, AREA, GEOG, PLACENAME, REGION, and SETTLEMENT.

Another example of a deviation from the assumption that an entity reference element contains no child elements and the text node of the element contains the unbroken string of the entity label that is to be used for the entity lookup would be if the TEI persName element was parsed into the child elements of forename and surname.

Andrew: can code be written that would be strip out any child elements (if encountered) in the 8 entity reference elements I outlined above (i.e., NAME, ORGNAME, PLACE, and TITLE [CWRC entry and Orlando], and persName, orgName, placeName, and title [TEI]) for the purposes of deriving the query string to perform the entity lookup?  I am assuming that obtaining the query lookup string would be one of the challenges of processing entity reference elements with any child elements, let alone one child element.

**Comment by ajmacdonald** [comment] 2015-09-22 18:09
I'll try and explain where I'm encountering difficulties.

When you create a place entity in an Orlando document from scratch, you select the type of place in the form (address, settlement, etc), which is what determines what child element gets created in the resulting markup (see the Annotation object forms -- Orlando elements and attributes google doc).

I have to reverse this process when loading documents, and also when converting markup to entities. To determine the type of place, I need to examine the XML. When we have perfectly valid XML like this:
```<PLACE><SETTLEMENT>Brantford</SETTLEMENT>,
<REGION>Ontario</REGION><GEOG REG="Canada">﻿</GEOG></PLACE>```
I can't determine what the place type is.

**Comment by brundin** [comment] 2015-09-22 19:25
Can we apply a geographic hierarchical heuristic wherein we assume the place reference element of interest is always the most granular and specific toponym?  So, the hierarchy, from the most granular to increasingly broader geographic terms, would be the following:

- ADDRESS
- PLACENAME
- SETTLEMENT
- REGION
- GEOG
- AREA

So, in the example you provided, SETTLEMENT is the "lowest" or most granular relative to REGION and GEOG, so the PLACE element REF attribute would be pointing to the place entity for "Brantford".

**Comment by ajmacdonald** [comment] 2015-09-24 16:59
I've implemented this hierarchy now.

A problem still remains, which pertains to how entities are being tracked internally and then converted to markup.
For the place entity, we're using the place type to determine what element should be inside of PLACE, e.g. SETTLEMENT.
In the Brantford example above, the PLACE element already contains SETTLEMENT, so when this place entity gets converted to markup upon export, an additional SETTLEMENT element will be added:
```
<PLACE><SETTLEMENT><SETTLEMENT>Brantford</SETTLEMENT>,
<REGION>Ontario</REGION><GEOG REG="Canada">﻿</GEOG></SETTLEMENT></PLACE>
```
I'm not yet sure what a good solution to this problem would be.

**Comment by SusanBrown** [comment] 2016-01-15 05:10
I just came across this buried in my emails. What exactly is causing the additional settlement tag to be added? I thought we were trying to add attributes to existing tags, rather than adding new ones. I must be forgetting something.

**Comment by ajmacdonald** [comment] 2016-01-26 20:42
The entity tagger will sometimes add tags in addition to attributes, depending on schema's entity mapping.

**Comment by SusanBrown** [comment] 2017-03-21 04:30
@colinraybrian pls test this and see if it still seems to be a problem

**Closed** 2022-04-12 19:26 UTC
Labels: enhancement, high priority, Confirm/clarify/respond, Blocked
